- {duration:30.0, offset: 0.0, speaker_id: spk.1, wav:quechua000573.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.2, wav:quechua000574.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.3, wav:quechua000575.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.4, wav:quechua000576.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.5, wav:quechua000577.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.6, wav:quechua000578.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.7, wav:quechua000579.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.8, wav:quechua000580.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.9, wav:quechua000581.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.10, wav:quechua000582.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.11, wav:quechua000583.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.12, wav:quechua000584.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.13, wav:quechua000585.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.14, wav:quechua000586.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.15, wav:quechua000587.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.16, wav:quechua000588.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.17, wav:quechua000589.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.18, wav:quechua000590.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.19, wav:quechua000591.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.20, wav:quechua000592.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.21, wav:quechua000593.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.22, wav:quechua000594.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.23, wav:quechua000595.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.24, wav:quechua000596.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.25, wav:quechua000597.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.26, wav:quechua000598.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.27, wav:quechua000599.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.28, wav:quechua000600.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.29, wav:quechua000601.wav}
- {duration:18.164, offset: 0.0, speaker_id: spk.30, wav:quechua000602.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.31, wav:quechua000603.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.32, wav:quechua000604.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.33, wav:quechua000605.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.34, wav:quechua000606.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.35, wav:quechua000607.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.36, wav:quechua000608.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.37, wav:quechua000609.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.38, wav:quechua000610.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.39, wav:quechua000611.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.40, wav:quechua000612.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.41, wav:quechua000613.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.42, wav:quechua000614.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.43, wav:quechua000615.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.44, wav:quechua000616.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.45, wav:quechua000617.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.46, wav:quechua000618.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.47, wav:quechua000619.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.48, wav:quechua000620.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.49, wav:quechua000621.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.50, wav:quechua000622.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.51, wav:quechua000623.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.52, wav:quechua000624.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.53, wav:quechua000625.wav}
- {duration:14.799, offset: 0.0, speaker_id: spk.54, wav:quechua000626.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.55, wav:quechua000627.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.56, wav:quechua000628.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.57, wav:quechua000629.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.58, wav:quechua000630.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.59, wav:quechua000631.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.60, wav:quechua000632.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.61, wav:quechua000633.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.62, wav:quechua000634.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.63, wav:quechua000635.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.64, wav:quechua000636.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.65, wav:quechua000637.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.66, wav:quechua000638.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.67, wav:quechua000639.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.68, wav:quechua000640.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.69, wav:quechua000641.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.70, wav:quechua000642.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.71, wav:quechua000643.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.72, wav:quechua000644.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.73, wav:quechua000645.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.74, wav:quechua000646.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.75, wav:quechua000647.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.76, wav:quechua000648.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.77, wav:quechua000649.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.78, wav:quechua000650.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.79, wav:quechua000651.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.80, wav:quechua000652.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.81, wav:quechua000653.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.82, wav:quechua000654.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.83, wav:quechua000655.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.84, wav:quechua000656.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.85, wav:quechua000657.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.86, wav:quechua000658.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.87, wav:quechua000659.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.88, wav:quechua000660.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.89, wav:quechua000661.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.90, wav:quechua000662.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.91, wav:quechua000663.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.92, wav:quechua000664.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.93, wav:quechua000665.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.94, wav:quechua000666.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.95, wav:quechua000667.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.96, wav:quechua000668.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.97, wav:quechua000669.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.98, wav:quechua000670.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.99, wav:quechua000671.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.100, wav:quechua000672.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.101, wav:quechua000673.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.102, wav:quechua000674.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.103, wav:quechua000675.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.104, wav:quechua000676.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.105, wav:quechua000677.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.106, wav:quechua000678.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.107, wav:quechua000679.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.108, wav:quechua000680.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.109, wav:quechua000681.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.110, wav:quechua000682.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.111, wav:quechua000683.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.112, wav:quechua000684.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.113, wav:quechua000685.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.114, wav:quechua000686.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.115, wav:quechua000687.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.116, wav:quechua000688.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.117, wav:quechua000689.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.118, wav:quechua000690.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.119, wav:quechua000691.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.120, wav:quechua000692.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.121, wav:quechua000693.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.122, wav:quechua000694.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.123, wav:quechua000695.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.124, wav:quechua000696.wav}
- {duration:30.0, offset: 0.0, speaker_id: spk.125, wav:quechua000697.wav}
